//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollageSystem.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SemesterStudent()
        {
            this.SemStudentCourses = new HashSet<SemStudentCours>();
        }
    
        public int SemStuID { get; set; }
        public int StudentID { get; set; }
        public int SemesterID { get; set; }
        public int MaxCreditHours { get; set; }
        public Nullable<double> SemesterGPA { get; set; }
        public Nullable<int> SemesterHours { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemStudentCours> SemStudentCourses { get; set; }
    }
}
