//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollageSystem.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semester()
        {
            this.CoursesSemesters = new HashSet<CoursesSemester>();
            this.SemesterStudents = new HashSet<SemesterStudent>();
        }
    
        public int SemID { get; set; }
        public string Year { get; set; }
        public int SemNumber { get; set; }
        public bool Editable { get; set; }
        public bool Added { get; set; }
        public bool finished { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesSemester> CoursesSemesters { get; set; }
        public virtual SemNumber SemNumber1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemesterStudent> SemesterStudents { get; set; }
    }
}
