//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollageSystem.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemStudentCours
    {
        public int SemStuID { get; set; }
        public int CourseID { get; set; }
        public Nullable<double> PractiseMarks { get; set; }
        public Nullable<double> OralMarks { get; set; }
        public Nullable<double> MidTermMarks { get; set; }
        public Nullable<double> YearWorkMarks { get; set; }
        public Nullable<double> FinalMarks { get; set; }
        public Nullable<bool> passed { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual SemesterStudent SemesterStudent { get; set; }
    }
}
